spring.application.name=parking


server.port=8585
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=kdt
spring.datasource.password=1234
mybatis.config-location = classpath:/mybatis/mybatis-config.xml
mybatis.mapper-locations=classpath:/mybatis/mapper/*.xml
# jsp íì´ì§ ê²½ë¡ ì¤ì 
spring.mvc.view.prefix= /WEB-INF/views/
spring.mvc.view.suffix= .jsp
#